# Etapa 1: Construir la aplicación
FROM node:23-alpine AS builder
# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos package.json y package-lock.json (o yarn.lock si usas Yarn)
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de los archivos del proyecto
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Etapa 2: Servir la aplicación en producción
FROM nginx:alpine

# Copiar los archivos de la aplicación construida desde la etapa anterior
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponer el puerto en el que Nginx servirá la aplicación
EXPOSE 5173

# Usa una imagen más liviana para producción
FROM node:23-alpine AS runner

# Ejecutar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]
